---
stages:
  - lint
  - build
  - test

variables:
  STICKY_RUNNER: runner2
  IMAGE: ${CI_REGISTRY}/as/sdp/as_drive:latest
  IMAGE_TEST: ${CI_PROJECT_PATH}_test:$CI_COMMIT_SHA
  IMAGE_RELEASE: ${CI_PROJECT_PATH}_release:$CI_COMMIT_SHA

lint:
  image: ${CI_REGISTRY}/as/sdp/infrastructure/as-build-tools
  stage: lint
  tags:
    - as-docker-pool
  script:
    - as_linter_python .
    - as_linter_clang .
    - as_package_lint .

build:
  stage: build
  tags:
    - as-docker-build
    - $STICKY_RUNNER
  before_script:
    # https://docs.gitlab.com/ee/ci/ssh_keys/
    - apk add bash git && rm -rf /var/cache/apk/*
    - mkdir -pm 700 ~/.ssh
    - eval $(ssh-agent -s)
    - cat $SSH_PRIVATE_KEY | tr -d '\r' | ssh-add -
  script:
    - sh ci_build.sh --build-arg CMAKE_BUILD_TYPE=Release --tag $IMAGE_RELEASE

test_release:
  image: $IMAGE_RELEASE
  stage: test
  tags:
    - as-docker-pool
    - $STICKY_RUNNER
  dependencies: []
  variables:
    FF_NETWORK_PER_BUILD: 1
    GIT_STRATEGY: none
  script:
    - cd /ws
    - source /opt/ros/$ROS_DISTRO/setup.sh
    - bash -c '[[ -z "$ROS_DOMAIN_ID" ]] || (echo "ROS_DOMAIN_ID=$ROS_DOMAIN_ID must be not set, otherwise tests would not be isolated" && false)'
    # as_localization_bag_tests - is a long running integration test and should be run manually
    - colcon test --packages-select $(colcon list -n --base-paths object_detection semantic_segmentation)
    - colcon test-result --verbose
