name: poetry-install
description: "Install dependencies with poetry if no cache was hit"

inputs:
  python-version:
    description: "Python version"
    required: true

runs:
  using: composite
  steps:
    - name: Setup python ${{ inputs.python-version }}
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
        echo "~/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Generate poetry.lock hash
      id: lock-hash
      run: echo "lock-hash=$(poetry lock --no-interaction --no-update | sha256sum | awk '{print $1}')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache packages
      id: cache-packages
      uses: actions/cache@v4
      with:
        path: "~/.cache/pypoetry"
        key: ${{ runner.os }}-python-${{ inputs.python-version }}-packages-${{ steps.lock-hash.outputs.lock-hash }}
        restore-keys: |
          ${{ runner.os }}-python-${{ inputs.python-version }}-packages-

    - name: Install dependencies
      if: steps.cache-packages.outputs.cache-hit != 'true'
      run: poetry install -v
      shell: bash
