name: semantic-pull-request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  workflow_call:

jobs:
  semantic-pull-request:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/semantic-pull-request.yaml@v1
