name: semantic-pull-request

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  semantic-pull-request:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/semantic-pull-request.yaml@v1
    timeout-minutes: 1
