name: Check spelling

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Retrieve spell check dictionary
        run: |
          curl --silent --show-error \
            --output .github/.cspell-base.json \
            https://raw.githubusercontent.com/tier4/autoware-spell-check-dict/main/cspell/.cspell.json

      - name: Merge .cspell.json
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq ".words += $(jq '.words' .cspell.json)" .github/.cspell-base.json > .github/.cspell.json

      - uses: streetsidesoftware/cspell-action@v2
        with:
          config: ".github/.cspell.json"
